### 1.1 수학과 파이썬 복습

### 1.1.1 벡터와 행렬

> **그림 1-1 벡터($\mathbf{x}$)와 행렬($A$)의 예**
$$ \mathbf{x} = 
    \begin{bmatrix}
    1 \\
    2 \\
    3 \\
    \end{bmatrix} ,\qquad A =     \begin{bmatrix}
    \bbox[yellow, 5px,border:2px solid red]{1} & \bbox[5px,border:2px solid red]{2} \\
    \bbox[yellow, 5px]{2} & 4 \\
    \bbox[yellow, 5px]{3} & 6 \\
    \end{bmatrix}
$$

> **그림 1-2 벡터의 표현법**
> $$ \mathbf{x}(열벡터) = 
    \begin{bmatrix}
    1 \\
    2 \\
    3 \\
    \end{bmatrix} \qquad  \mathbf{x}^T(행벡터) = \begin{bmatrix}
    1 & 2 & 3\\
    \end{bmatrix}
$$

이 책에서는 구현 편의를 고려하여 '행벡터'로 다룸

In [14]:
import numpy as np

x = np.array([1, 2, 3])
x.__class__

numpy.ndarray

In [15]:
x.shape

(3,)

In [16]:
x.ndim

1

In [17]:
W = np.array([[1, 2, 3], [4, 5, 6]])
W.shape

(2, 3)

In [21]:
W.ndim

2

### 1.1.2 행렬의 원소별 연산

In [28]:
W = np.array([[1, 2, 3], [4, 5, 6]]) # 2 x 3
X = np.array([[0, 1, 2], [3, 4, 5]]) # 2 x 3

element 연산

In [33]:
# 합
W + X

array([[ 1,  3,  5],
       [ 7,  9, 11]])

In [32]:
# 곱
W * X

array([[ 0,  2,  6],
       [12, 20, 30]])

### 1.1.3 브로드캐스트

In [46]:
A = np.array([[1,2] , [3, 4]])
A * 10

array([[10, 20],
       [30, 40]])

> 그림 1-3 브로드캐스트의 예 : Scalor 값인 `10`이 2x2 행렬로 ㅊ


![alt text](https://raw.githubusercontent.com/DeepHaeJoong/DeepLearningFromScratch_II/master/PNG/Figure%201-3.PNG?token=AF5I4WAQIMHZO2U4HFISZI2437BN2 "Title")

In [47]:
A = np.array([[1, 2], [3, 4]])
b = np.array(([10, 20]))
A * b

array([[10, 40],
       [30, 80]])

### 1.1.4 벡터의 내적과 행렬의 곱

$$
\mathbf{x} \bullet \mathbf{y} = x_1y_1 + x_2y_2 + \ldots + x_ny_n\\
$$

벡터의 내적은 직관적으로 '두 벡터가 얼마나 같은 방향을 향하고 있는가'를 나타냄. 벡터의 길이가 1인 경우로 한정하면, 완전히 같은 방향을 향하는 두 벡터의 내적은 1이 된다. 반대로 반대 방향을 향하는 두 벡터의 내적은 -1이다.

In [41]:
# 벡터의 내적
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])
np.dot(a,b)

32

In [42]:
# 행렬의 곱
A = np.array([[1, 2], [3, 4]])
B = np.array([[4, 5], [6, 7]])
np.matmul(A, B)

array([[16, 19],
       [36, 43]])

In [45]:
np.dot(A, B)

array([[16, 19],
       [36, 43]])

[100 numpy exercises](https://github.com/rougier/numpy-100/blob/master/100_Numpy_exercises_no_solution.ipynb)

### 1.1.5 행렬 형상 확인